apiVersion: v1
kind: Pod
metadata:
  labels:
    run: mysql
  name: mysql
spec:
  containers:
  - image: mysql:8.0.22
    name: mysql
    env:
    - name: MYSQL_ROOT_PASSWORD
      value: "example"
  restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  labels:
    run: mysql
  name: db
spec:
  ports:
  - port: 3306
    protocol: TCP
    targetPort: 3306
  selector:
    run: mysql
  type: ClusterIP
